Hide type error on one line
> app.py:573: error: "AppContext" has no attribute "setdefault"

This is a workaround for a type bug introduced in Flask 2.0.0 (already
fixed in pallets/flask#4042 [1], but 2.0.1 not yet released).

[1]: https://github.com/pallets/flask/pull/4042